version: '3.8'

services:
  store_db:
    container_name: postgres_container
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /pg_data:/var/lib/postgresql/data/
    ports:
      - 6777:8080